project:
  type: website
  render:
    - /slides/formation_light.qmd
    - /slides/formation_full.qmd
    - /slides/formation_manageurs.qmd
    - index.qmd
    - "/cards/**/*.qmd"

website:
  title: "`utilitR`"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://www.book.utilitr.org
        text: Documentation
      - href: https://datalab.sspcloud.fr
        text: "SSPCloud"
      - icon: github
        href: https://github.com/InseeFrLab/utilitr
    background: "#4758AB"
  twitter-card:
    image: /cards/version-light/cheetah.png

format:
  html:
    theme: [cosmo, style.scss]
    css: styles.css
    toc: true

